manifest:
  remotes:
    - name: PanKnst
      url-base: https://github.com/PanKnst
  projects:
    - name: zmk
      remote: PanKnst
      revision: main
      import: app/west.yml
  self:
    path: config
